### ISSUE TITLE
Analisar sistemas de recomendação em Python

### ISSUE THREAD

**Issue by ggrocco** [ggrocco/recomenda_easy#3]
Buscar ideias de sistemas de recomendação colaborativo e por filtro.

**Comment by tpaim** [comment]
https://movile.blog/sistemas-de-recomendacao-com-filtros-colaborativos/
https://www.maxwell.vrac.puc-rio.br/13225/13225_4.PDF
https://www.cin.ufpe.br/~rbcp/dissertacoes/dissertacaoIAS.pdf

**Comment by tpaim** [comment]
https://www.maxwell.vrac.puc-rio.br/13225/13225_4.PDF
